### ISSUE TITLE
question in arxiv paper

### ISSUE THREAD

**Issue by jdily** [ToniCreswell/attribute-cVAEGAN#1]
Hi, 
I just read the paper and found this repo.
I have a question in terms of the paper:
* in eq.3, the reconstruction loss should be L_{mse} (\hat{x}, x) instead of L_{bce}?

**Comment by ToniCreswell** [comment]
Hi,

Thanks for your question and interest. It is bce. You could try mse but in general I find using bce with normalized images to work best.

Thanks,
Toni.

Sent from my iPhone

On Dec 4, 2017, at 22:53, icshen <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I just read the paper and found this repo.
I have a question in terms of the paper:

  *   in eq.3, the reconstruction loss should be L_{mse} (\hat{x}, x) instead of L_{bce}?

**Comment by jdily** [comment]
Hi, I see.
thx for your reply. 
I will try to use bce with normalized image to do some experiment, thx!

**Comment by pixieDoug** [comment]
Could someone link to the arxiv paper referenced above?

Thanks!
Doug

**Comment by ToniCreswell** [comment]
https://arxiv.org/abs/1711.05175

**Comment by pixieDoug** [comment]
@ToniCreswell Thank you!  _Extremely_ helpful!!
